### ISSUE TITLE
stack trace when processing full wikipedia data dump

### ISSUE THREAD

**Issue by jprorama** [annacrombie/clean_wiki#1]
I'm getting a stack trace when I reach about the 128th exported article in the wikipedia dump.   The error is about unreachable code being reached in the table.rs file of parse_wiki_text, so I'm not sure if this caused by the library code itself or how we happen to be calling it.

I'm invoking the code as:
```
srun cargo run ../cs762/project/data/enwiki-20181120-pages-articles.xml.bz2 > ../cs762/project/data/wiki-sample.txt
```

Here's the stack trace.
```
     Running `target/debug/clean_wiki ../cs762/project/data/enwiki-20181120-pages-articles.xml.bz2`          [38/3125]
thread 'main' panicked at 'internal error: entered unreachable code', /home/jpr/.cargo/registry/src/github.com-1ecc6299db9ec823/parse_wiki_text-0.1.2/src/table.rs:615:14
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::begin_panic
             at libstd/panicking.rs:411
   6: parse_wiki_text::table::get_table
             at /home/jpr/.cargo/registry/src/github.com-1ecc6299db9ec823/parse_wiki_text-0.1.2/src/table.rs:615
   7: parse_wiki_text::table::parse_heading_cell
             at /home/jpr/.cargo/registry/src/github.com-1ecc6299db9ec823/parse_wiki_text-0.1.2/src/table.rs:8
   8: parse_wiki_text::parse::parse
             at /home/jpr/.cargo/registry/src/github.com-1ecc6299db9ec823/parse_wiki_text-0.1.2/src/parse.rs:77
   9: parse_wiki_text::configuration::<impl parse_wiki_text::Configuration>::parse
             at /home/jpr/.cargo/registry/src/github.com-1ecc6299db9ec823/parse_wiki_text-0.1.2/src/configuration.rs:1
54
  10: clean_wiki::clean_text
             at src/main.rs:45
  11: clean_wiki::clean_page
             at src/main.rs:39
  12: clean_wiki::parse::{{closure}}
             at src/main.rs:87
```

**Comment by annacrombie** [comment]
Yeah I was getting this last night as well.  I'm not sure what the problem is but I suspect parse_wiki_text is getting a page it can't handle.  I'm looking into it now.

**Comment by annacrombie** [comment]
I can confirm it is an issue with parse_wiki_text.  It is reproduced when parsing this article https://en.wikipedia.org/Special:Export/Nick_Cave

**Comment by annacrombie** [comment]
Okay, the problem occurs when parsing a link with title "Dig, Lazarus, Dig!!!"  It is interpreting the !!! as a table start and is dying (of course).  I'm suprised the author didn't catch this bug.

**Comment by annacrombie** [comment]
Okay I fixed it by just ignoring that case in my fork of parse_wiki_text.
